modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/refinedmods/refinedpipes"
[[mods]]
modId="refinedpipes"
version="${version}"
displayName="Refined Pipes"
updateJSONURL="https://refinedmods.com/refined-pipes/update.json"
displayURL="https://refinedmods.com/refined-pipes"
authors="Refined Mods"
description='''
Refined Pipes is a Minecraft mod that adds pipes.
'''
